# Generated by Django 3.1.6 on 2021-02-10 06:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Thing',
            fields=[
                ('code', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('description', models.CharField(blank=True, max_length=50, null=True)),
                ('date', models.DateField(blank=True, null=True)),
                ('stat_one', models.CharField(default='99', max_length=2)),
                ('stat_two', models.CharField(default='9', max_length=1)),
            ],
        ),
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=10)),
                ('rating', models.CharField(max_length=3)),
                ('score', models.IntegerField(blank=True, default=0)),
                ('thing', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='records.thing')),
            ],
        ),
    ]
